name: format

run-name: pytests and formatting

on:
  pull_request:
    types:
      - opened

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install pytest
          pip install torchvision
          pip install torch
      - run: pytest

  format-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pip install black
      - run: chmod +x ./reformat.sh
      - run: source reformat.sh
      - run: echo ${GITHUB_REF##*/}
      - run: git add .
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git config --global user.name "github-actions[bot]"
      - run: git commit -m "Auto-Reformat"
      - run: echo "git fetch origin ${GITHUB_REF##*/}"
      - run: git push origin ${GITHUB_REF##*/}