name: githubworkflows

run-name: ${{github.actor}} has made this cool file.

on: [push]

jobs:


  format-code:

    runs-on: ubuntu-latest


    steps:
      
      - run: ../../unittests/test_data.py