#image: continuumio/miniconda3:latest
name: format

run-name: ${{github.actor}} has made this cool file.

on: [push]

jobs:

  format-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pip install black
      - run: chmod +x ./reformat.sh
      - run: source reformat.sh