#image: continuumio/miniconda3:latest
name: format

run-name: ${{github.actor}} has made this cool file.

on: [push]

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install pytest
          pip install torchvision
          pip install torch
      - run: pytest

  format-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pip install black
      - run: chmod +x ./reformat.sh
      - run: source reformat.sh
      - run: git add .
      - run: git config --global user.email "akash.bhagran@hotmail.com"
      - run: git config --global user.name "Akash Bhagran"
      - run: git commit -m "Auto-Reformat"
      - run: echo "git fetch origin ${GITHUB_REF##*/}"
      - run: git push origin ${GITHUB_REF##*/}