name: githubworkflows

run-name: ${{github.actor}} has made this cool file.

on: [push]

jobs:

  image: python:3.8

  format-code:

    runs-on: ubuntu-latest

    script:

      - black . --check --exclude '\.venv/|\.local/|\.cache/|\.git/'

    #steps:
      
     # - run: 